import { useEffect, useMemo, useState } from "react";
import { Copy, ExternalLink, FileDown, FolderOpen, Radio, Square, Terminal, Waves } from "lucide-react";
import { ErrorPanel } from "../../shared/components/ErrorPanel";
import { PageHeader } from "../../shared/components/PageHeader";
import { Badge, Button, Card, DataLine, EmptyState, SectionTitle } from "../../shared/components/ui";
import { desktopApi } from "../../shared/lib/tauri";
import type { TosuLiveSnapshot, TosuLogEntry, TosuStatus } from "../../shared/types/osu";

const TOSU_RELEASES = "https://github.com/tosuapp/tosu/releases/latest";
const LYRICS_RELEASES = "https://github.com/HollisMeynell/tosu-lyrics/releases/latest";

function formatNumber(value: number | null | undefined, digits = 0) { return value === null || value === undefined ? "—" : value.toLocaleString(undefined, { maximumFractionDigits: digits, minimumFractionDigits: digits }); }
function formatTime(value: number | null | undefined) { if (value === null || value === undefined) return "—"; const seconds = Math.max(0, Math.floor(value / 1000)); return `${Math.floor(seconds / 60)}:${String(seconds % 60).padStart(2, "0")}`; }

function LivePanel({ live }: { live: TosuLiveSnapshot | null }) {
  if (!live) return <EmptyState icon={<Waves className="size-5" />} title="等待 tosu 实时数据" description="启动 tosu 并打开 osu! 后，这里会显示当前谱面与游戏状态。" />;
  const title = [live.artist, live.title].filter(Boolean).join(" — ") || "未读取到当前谱面";
  return <Card className="p-6"><div className="flex items-start justify-between gap-4"><div><Badge tone="pink"><Radio className="size-3.5" />{live.state ?? "已连接"}</Badge><h2 className="mt-4 text-xl font-semibold text-white">{title}</h2><p className="mt-1 text-sm text-slate-500">{[live.difficulty, live.mode, live.mods].filter(Boolean).join(" · ") || "等待游戏状态"}</p></div><div className="text-right"><p className="font-mono text-lg text-cyan-100">{formatTime(live.song_time_ms)} / {formatTime(live.song_length_ms)}</p><p className="mt-1 text-xs text-slate-500">歌曲进度</p></div></div><div className="mt-6 grid gap-x-6 sm:grid-cols-2 xl:grid-cols-4"><DataLine label="分数" value={formatNumber(live.score)} /><DataLine label="连击" value={`${formatNumber(live.combo)} / ${formatNumber(live.max_combo)}`} /><DataLine label="准确率" value={live.accuracy === null ? "—" : `${formatNumber(live.accuracy, 2)}%`} /><DataLine label="PP" value={`${formatNumber(live.pp_current, 2)} / FC ${formatNumber(live.pp_fc, 2)}`} /><DataLine label="300 / 100 / 50" value={`${formatNumber(live.hit_300)} / ${formatNumber(live.hit_100)} / ${formatNumber(live.hit_50)}`} /><DataLine label="Miss" value={formatNumber(live.misses)} /></div></Card>;
}

function LogPanel({ entries }: { entries: TosuLogEntry[] }) {
  const [onlyIssues, setOnlyIssues] = useState(false);
  const visible = onlyIssues ? entries.filter((entry) => entry.level !== "info") : entries;
  const colors = { info: "text-cyan-200", warning: "text-amber-200", error: "text-rose-200" };
  return <Card className="min-h-72 overflow-hidden p-0"><div className="flex items-center justify-between gap-3 border-b border-white/[0.07] px-5 py-4"><div className="flex items-center gap-2"><Terminal className="size-4 text-cyan-200" /><SectionTitle title="本次运行日志" description="仅在本次 OPP 运行期间保留。" /></div><Button onClick={() => setOnlyIssues((value) => !value)} size="sm" variant="ghost">日志级别：{onlyIssues ? "警告及错误" : "全部"}</Button></div><div className="max-h-80 overflow-auto bg-black/20 p-4 font-mono text-xs leading-6">{visible.length ? visible.map((entry, index) => <div className="grid grid-cols-[72px_58px_64px_1fr] gap-2 text-slate-400" key={`${entry.at}-${index}`}><span className="text-slate-600">{new Date(entry.at).toLocaleTimeString()}</span><span className={colors[entry.level]}>{entry.level}</span><span className="text-slate-500">{entry.stream}</span><span className="break-all">{entry.message}</span></div>) : <p className="text-slate-600">没有符合当前级别的日志。</p>}</div></Card>;
}

function LyricsCard({ status, busy, onChoose }: { status: TosuStatus; busy: boolean; onChoose: () => void }) {
  const lyrics = status.lyrics;
  const copy = async () => { await navigator.clipboard.writeText(lyrics.proxy_url); };
  return <Card className="p-6"><div className="flex items-start justify-between gap-4"><SectionTitle title="tosu-lyrics 歌词代理" description="为 OBS 浏览器源提供实时歌词；OPP 仅引导安装，不分发插件。" /><Badge tone={lyrics.running ? "success" : "neutral"}>{lyrics.owned_by_opp ? "OPP 管理中" : lyrics.running ? "外部运行中" : "未运行"}</Badge></div><p className="mt-4 truncate rounded-xl border border-white/[0.07] bg-black/20 px-3 py-2.5 font-mono text-xs text-slate-300">{lyrics.executable_path ?? "尚未选择 tosu-proxy.exe"}</p><div className="mt-4"><DataLine label="OBS 歌词代理地址" value={<span className="inline-flex max-w-64 items-center gap-2"><span className="truncate font-mono text-xs">{lyrics.proxy_url}</span><button aria-label="复制歌词代理地址" className="text-cyan-200" onClick={() => void copy()} type="button"><Copy className="size-3.5" /></button></span>} /></div><div className="mt-4 flex flex-wrap gap-3"><Button onClick={() => void desktopApi.openExternal(LYRICS_RELEASES)} size="sm"><FileDown className="size-4" />歌词插件下载页</Button><Button loading={busy} onClick={onChoose} size="sm"><FolderOpen className="size-4" />选择 tosu-proxy.exe</Button><Button disabled={!lyrics.running} onClick={() => void desktopApi.openExternal(lyrics.proxy_url)} size="sm"><ExternalLink className="size-4" />打开歌词页面</Button></div><p className="mt-4 text-xs leading-5 text-slate-500">将发行包解压到 tosu 根目录后选择其中的 tosu-proxy.exe；配置完成后，每次由 OPP 启动 tosu 都会自动启动歌词代理。</p></Card>;
}

export function TosuPage() {
  const [status, setStatus] = useState<TosuStatus | null>(null);
  const [logs, setLogs] = useState<TosuLogEntry[]>([]);
  const [live, setLive] = useState<TosuLiveSnapshot | null>(null);
  const [error, setError] = useState<unknown>(null);
  const [busy, setBusy] = useState<"choose" | "lyrics" | "start" | "stop" | null>(null);
  const refresh = async () => { try { const [nextStatus, nextLogs] = await Promise.all([desktopApi.getTosuStatus(), desktopApi.getTosuLogs()]); setStatus(nextStatus); setLogs(nextLogs); setError(null); } catch (value) { setError(value); } };
  useEffect(() => { const initial = window.setTimeout(() => void refresh(), 0); const timer = window.setInterval(() => void refresh(), 4000); let disposed = false; let unsubscribe: (() => void) | undefined; void Promise.all([desktopApi.onTosuLog((entry) => { if (!disposed) setLogs((current) => [...current.slice(-499), entry]); }), desktopApi.onTosuLiveData((snapshot) => { if (!disposed) setLive(snapshot); })]).then(([offLog, offLive]) => { if (disposed) { offLog(); offLive(); } else unsubscribe = () => { offLog(); offLive(); }; }); return () => { disposed = true; window.clearTimeout(initial); window.clearInterval(timer); unsubscribe?.(); }; }, []);
  const choose = async () => { setBusy("choose"); setError(null); try { const path = await desktopApi.chooseTosuExecutable(status?.executable_path); if (path) setStatus(await desktopApi.setTosuExecutable(path)); } catch (value) { setError(value); } finally { setBusy(null); } };
  const chooseLyrics = async () => { setBusy("lyrics"); setError(null); try { const path = await desktopApi.chooseTosuLyricsExecutable(status?.lyrics.executable_path); if (path) setStatus(await desktopApi.setTosuLyricsExecutable(path)); } catch (value) { setError(value); } finally { setBusy(null); } };
  const start = async () => { setBusy("start"); setError(null); try { await desktopApi.startTosu(); await refresh(); } catch (value) { setError(value); } finally { setBusy(null); } };
  const stop = async () => { setBusy("stop"); setError(null); try { await desktopApi.stopTosu(); await refresh(); } catch (value) { setError(value); } finally { setBusy(null); } };
  const connection = useMemo(() => status?.api_reachable ? <Badge tone="success">API 已连接</Badge> : <Badge tone="warning">API 未连接</Badge>, [status]);
  return <><PageHeader eyebrow="Live integration" title="tosu 直播集成" description="让 OPP 代为静默启动 tosu、歌词代理，并集中查看直播实时数据与运行日志。" actions={connection} />{error ? <div className="mb-5"><ErrorPanel error={error} onRetry={() => void refresh()} /></div> : null}<div className="grid gap-5 xl:grid-cols-[1.15fr_.85fr]"><div className="space-y-5"><Card className="p-6"><div className="flex items-start justify-between gap-5"><div><div className="flex items-center gap-2"><Radio className="size-5 text-pink-200" /><SectionTitle title="tosu 服务" description="OPP 不内置 tosu；请从官方发行页下载并解压后选择 tosu.exe。" /></div><p className="mt-5 truncate rounded-xl border border-white/[0.07] bg-black/20 px-3 py-2.5 font-mono text-xs text-slate-300">{status?.executable_path ?? "尚未选择 tosu.exe"}</p></div><Badge tone={status?.running ? "success" : "neutral"}>{status?.owned_by_opp ? "OPP 管理中" : status?.running ? "外部运行中" : "未运行"}</Badge></div><div className="mt-5 flex flex-wrap gap-3"><Button onClick={() => void desktopApi.openExternal(TOSU_RELEASES)}><FileDown className="size-4" />官方下载页</Button><Button loading={busy === "choose"} onClick={() => void choose()}><FolderOpen className="size-4" />选择 tosu.exe</Button>{status?.owned_by_opp ? <Button loading={busy === "stop"} onClick={() => void stop()} variant="danger"><Square className="size-4" />停止 tosu</Button> : <Button disabled={!status?.installed} loading={busy === "start"} onClick={() => void start()} variant="primary"><Radio className="size-4" />启动 tosu</Button>}<Button disabled={!status?.running} onClick={() => void desktopApi.openExternal(status?.dashboard_url ?? "http://127.0.0.1:24050")}><ExternalLink className="size-4" />打开配置网站</Button></div>{status?.last_error ? <p className="mt-4 text-xs text-amber-200">{status.last_error}</p> : null}</Card><LivePanel live={live} /></div><div className="space-y-5">{status ? <LyricsCard busy={busy === "lyrics"} onChoose={() => void chooseLyrics()} status={status} /> : null}<Card className="p-6"><SectionTitle title="连接状态" description="实时数据来自 tosu v2 WebSocket API。" /><div className="mt-4"><DataLine label="API 地址" value={<span className="max-w-52 truncate font-mono text-xs">{status?.api_base_url ?? "正在读取"}</span>} /><DataLine label="服务状态" value={status?.api_reachable ? "可用" : "不可用"} /><DataLine label="进程归属" value={status?.owned_by_opp ? "由 OPP 启动" : status?.running ? "外部进程" : "—"} /></div><p className="mt-4 text-xs leading-5 text-slate-500">可在“设置 &gt; 常规”中修改 tosu API 地址。</p></Card><LogPanel entries={logs} /></div></div></>;
}
