import { useEffect, useMemo, useRef, useState } from "react";
import { Ban, CheckCircle2, DownloadCloud, FolderOpen, Gauge, ListPlus, Trash2, X } from "lucide-react";
import { Badge, Button, Card } from "../../shared/components/ui";
import { desktopApi } from "../../shared/lib/tauri";
import type { BeatmapDownloadProgress, BeatmapDownloadResult, CommandError, OnlineBeatmapSearchQuery, OnlineBeatmapset } from "../../shared/types/osu";
import { useSettings } from "../settings/api";

const downloadDirectoryKey = "opp:beatmap-download-directory";

export function BeatmapDownloadPanel({ availableTotal, query, queue, onClear, onRemove, onReplace }: { availableTotal: number | null; query: OnlineBeatmapSearchQuery; queue: OnlineBeatmapset[]; onClear: () => void; onRemove: (beatmapsetId: number) => void; onReplace: (items: OnlineBeatmapset[]) => void }) {
  const [destination, setDestination] = useState(() => localStorage.getItem(downloadDirectoryKey) ?? "");
  const settings = useSettings();
  const [collectLimit, setCollectLimit] = useState(100);
  const [provider, setProvider] = useState<"catboy" | "nerinyan" | "none">("catboy");
  const [collecting, setCollecting] = useState(false);
  const [downloading, setDownloading] = useState(false);
  const [overwrite, setOverwrite] = useState(false);
  const [progress, setProgress] = useState<BeatmapDownloadProgress | null>(null);
  const [result, setResult] = useState<BeatmapDownloadResult | null>(null);
  const [error, setError] = useState<string | null>(null);
  const speedRef = useRef({ processed: 0, at: 0 });
  const [speed, setSpeed] = useState(0);

  const effectiveDestination = destination || settings.data?.beatmap_download_directory || "";

  useEffect(() => { let dispose: () => void = () => undefined; desktopApi.onBeatmapDownloadProgress((next) => { const now = performance.now(); const previous = speedRef.current; if (previous.at && next.processed > previous.processed) setSpeed((next.processed - previous.processed) / ((now - previous.at) / 60000)); speedRef.current = { processed: next.processed, at: now }; setProgress(next); }).then((unlisten) => { dispose = unlisten; }); return () => dispose(); }, []);
  const percent = useMemo(() => progress?.total ? Math.min(100, progress.processed / progress.total * 100) : 0, [progress]);
  const chooseDirectory = async () => { try { const selected = await desktopApi.chooseBeatmapDownloadDirectory(effectiveDestination || null); if (selected) { setDestination(selected); localStorage.setItem(downloadDirectoryKey, selected); await desktopApi.updateSettings({ ...(settings.data ?? { reduce_motion: false, beatmap_download_directory: null, replay_export_directory: null }), beatmap_download_directory: selected }); } } catch (caught) { setError((caught as CommandError).message ?? String(caught)); } };
  const collectMatches = async () => { setCollecting(true); setError(null); setResult(null); try { const collected = await desktopApi.collectOnlineBeatmapsets({ ...query, cursor_string: null }, collectLimit); onReplace(collected.items.filter((item) => !item.availability?.download_disabled)); if (collected.truncated) setError(`结果超过 ${collectLimit} 条，已加入前 ${collectLimit} 条。`); } catch (caught) { setError((caught as CommandError).message ?? String(caught)); } finally { setCollecting(false); } };
  const startDownload = async () => { let target = effectiveDestination; if (!target) { target = await desktopApi.chooseBeatmapDownloadDirectory(null) ?? ""; if (!target) return; setDestination(target); localStorage.setItem(downloadDirectoryKey, target); } setDownloading(true); setError(null); setResult(null); setProgress(null); setSpeed(0); speedRef.current = { processed: 0, at: 0 }; try { setResult(await desktopApi.downloadOnlineBeatmapsets({ destination: target, provider, overwrite, items: queue.map((item) => ({ beatmapset_id: item.id, artist: item.artist, title: item.title })) })); } catch (caught) { setError((caught as CommandError).message ?? String(caught)); } finally { setDownloading(false); } };

  return <Card className="sticky top-[120px] overflow-hidden"><div className="border-b border-white/[0.08] px-5 py-4"><div className="flex items-center justify-between"><div><h2 className="text-base font-semibold text-white">下载队列</h2><p className="mt-1 text-sm text-slate-500">镜像站仅提供下载资源</p></div><Badge tone={queue.length ? "pink" : "neutral"}>{queue.length}</Badge></div></div><div className="space-y-5 p-5">
    <button className="flex w-full items-center gap-3 rounded-xl border border-white/[0.09] bg-black/15 px-3 py-3 text-left text-base text-slate-300 transition hover:border-white/20" onClick={chooseDirectory} type="button"><FolderOpen className="size-5 shrink-0 text-cyan-200" /><span className="min-w-0 flex-1 truncate">{effectiveDestination || "选择保存目录"}</span></button>
    <label className="block"><span className="mb-2 block text-sm font-medium text-slate-300">下载适配器</span><select className="w-full rounded-xl border border-white/[0.09] bg-[#0b101b] px-3 py-3 text-sm text-slate-200 outline-none focus:border-cyan-300/45" disabled={downloading || collecting} onChange={(event) => setProvider(event.target.value as typeof provider)} value={provider}><option value="catboy">Catboy（推荐）</option><option value="nerinyan">Nerinyan</option><option value="none">不使用镜像</option></select></label>
    <div className="rounded-2xl border border-cyan-300/10 bg-cyan-300/[0.035] p-4"><div className="flex items-center justify-between gap-3"><div><p className="text-sm font-medium text-slate-200">按当前筛选加入</p><p className="mt-1 text-sm text-slate-500">官网匹配 {availableTotal ?? "—"} 条</p></div><select className="rounded-lg border border-white/[0.09] bg-[#0b101b] px-2 py-2 text-sm text-slate-300" disabled={collecting || downloading} onChange={(event) => setCollectLimit(Number(event.target.value))} value={collectLimit}>{[50, 100, 250, 500].map((limit) => <option key={limit} value={limit}>{limit} 条</option>)}</select></div><Button className="mt-3 w-full" disabled={downloading} loading={collecting} onClick={collectMatches} size="sm"><ListPlus className="size-4" />加入当前结果</Button></div>
    <div className="max-h-72 space-y-1 overflow-y-auto pr-1">{queue.length ? queue.slice(0, 100).map((item, index) => <div className="group flex items-center gap-3 rounded-xl px-2 py-2.5 hover:bg-white/[0.04]" key={item.id}><span className="w-6 shrink-0 text-center font-mono text-sm text-slate-600">{index + 1}</span><div className="min-w-0 flex-1"><p className="truncate text-sm text-slate-300">{item.title}</p><p className="truncate text-xs text-slate-600">{item.artist} · {item.creator}</p></div><button aria-label="移除谱面" className="grid size-8 place-items-center rounded-lg text-slate-600 opacity-0 transition hover:bg-white/[0.08] hover:text-white group-hover:opacity-100" disabled={downloading} onClick={() => onRemove(item.id)} type="button"><X className="size-4" /></button></div>) : <div className="rounded-xl border border-dashed border-white/[0.1] px-4 py-10 text-center text-sm leading-6 text-slate-600">从结果卡片选择谱面，或按当前筛选批量加入。</div>}</div>
    {progress ? <div className="rounded-xl border border-white/[0.08] bg-black/15 p-4"><div className="flex items-center justify-between gap-3 text-sm"><span className="max-w-[180px] truncate text-slate-400">{progress.current_title ?? progress.message ?? "正在下载"}</span><span className="font-mono text-cyan-200">{progress.processed}/{progress.total}</span></div><div className="mt-3 h-2 overflow-hidden rounded-full bg-white/[0.08]"><div className="h-full rounded-full bg-gradient-to-r from-pink-400 to-cyan-300 transition-all" style={{ width: `${percent}%` }} /></div><div className="mt-3 flex items-center justify-between text-xs text-slate-500"><span className="inline-flex items-center gap-1.5"><Gauge className="size-3.5" />{progress.phase === "finished" ? "下载完成" : progress.phase === "cancelled" ? "已取消" : "下载中"}</span><span>{speed > 0 ? `${speed.toFixed(1)} 个/分钟` : "等待速度"}</span></div></div> : null}
    {result ? <div className="flex items-start gap-3 rounded-xl border border-emerald-300/10 bg-emerald-300/[0.05] p-4 text-sm text-emerald-100"><CheckCircle2 className="mt-0.5 size-5 shrink-0" />完成 {result.completed}，跳过 {result.skipped}，失败 {result.failed}</div> : null}{error ? <div className="rounded-xl border border-amber-300/10 bg-amber-300/[0.05] p-4 text-sm leading-6 text-amber-100">{error}</div> : null}
    <label className="flex items-center gap-3 text-sm text-slate-500"><input checked={overwrite} disabled={downloading} onChange={(event) => setOverwrite(event.target.checked)} type="checkbox" />覆盖同名 .osz 文件</label><div className="flex gap-3">{downloading ? <Button className="flex-1" onClick={() => desktopApi.cancelOnlineBeatmapDownload()} variant="danger"><Ban className="size-4" />取消下载</Button> : <Button className="flex-1" disabled={!queue.length || provider === "none" || collecting} onClick={startDownload} variant="primary"><DownloadCloud className="size-4" />开始下载</Button>}<Button aria-label="清空队列" disabled={!queue.length || downloading} onClick={onClear} size="icon" variant="ghost"><Trash2 className="size-5" /></Button></div><p className="text-sm leading-6 text-slate-600">谱面信息和筛选来自官网；镜像站仅提供文件资源。</p>
  </div></Card>;
}
