import { useState } from "react";
import * as Switch from "@radix-ui/react-switch";
import { useQueryClient } from "@tanstack/react-query";
import { Check, Copy, ExternalLink, FolderOpen, LogOut, MonitorCog, Trash2 } from "lucide-react";
import { useMode } from "../../app/ModeContext";
import { PageHeader } from "../../shared/components/PageHeader";
import { ModeSwitch } from "../../shared/components/ModeSwitch";
import { Badge, Button, Card, DataLine, SectionTitle } from "../../shared/components/ui";
import { desktopApi } from "../../shared/lib/tauri";
import { authQueryKey, useAuthStatus } from "../auth/api";
import { localSourcesKey, useLocalSources } from "../local-analysis/api";
import { settingsQueryKey, useSettings } from "./api";
import type { AppSettings } from "../../shared/types/osu";

const REPOSITORY = "https://github.com/L1rics06/OPP";

function GameDirectoryCard() {
  const { client, ruleset, setRuleset } = useMode();
  const queryClient = useQueryClient();
  const source = useLocalSources().data?.find((item) => item.client === client);
  const [busy, setBusy] = useState(false);
  const choose = async () => { setBusy(true); try { const selected = await desktopApi.chooseLocalDirectory(source?.install_root ?? source?.data_root); if (selected) { await desktopApi.setLocalSource(client, selected); await queryClient.invalidateQueries({ queryKey: localSourcesKey }); } } finally { setBusy(false); } };
  const reset = async () => { setBusy(true); try { await desktopApi.resetLocalSource(client); await queryClient.invalidateQueries({ queryKey: localSourcesKey }); } finally { setBusy(false); } };
  return <Card className="p-6"><SectionTitle title="游戏目录" description="用于读取当前客户端的截图、回放和本地谱面。" /><div className="mt-5 rounded-2xl border border-white/[0.08] bg-white/[0.035] p-4"><div className="flex items-center justify-between gap-4"><p className="text-base font-semibold text-white">默认模式</p><Badge tone="cyan">{client === "stable" ? "Stable" : "Lazer"}</Badge></div><div className="mt-3"><ModeSwitch value={ruleset} onChange={setRuleset} /></div><p className="mt-4 truncate font-mono text-sm text-slate-300">{source?.install_root ?? source?.data_root ?? "正在检测"}</p></div><div className="mt-4 flex gap-3"><Button disabled={busy} loading={busy} onClick={choose} size="sm"><FolderOpen className="size-4" />选择目录</Button>{source?.mode === "override" ? <Button disabled={busy} onClick={reset} size="sm">恢复自动检测</Button> : null}</div></Card>;
}

function DirectorySettingsCard({ settings, onSaved }: { settings: { beatmap_download_directory?: string | null; replay_export_directory?: string | null }; onSaved: (value: { beatmap_download_directory: string | null; replay_export_directory: string | null }) => void }) {
  const [busy, setBusy] = useState<string | null>(null);
  const choose = async (key: "beatmap_download_directory" | "replay_export_directory", title: string) => { setBusy(key); try { const value = await desktopApi.chooseDirectory(title, settings[key]); if (value) onSaved({ beatmap_download_directory: key === "beatmap_download_directory" ? value : settings.beatmap_download_directory ?? null, replay_export_directory: key === "replay_export_directory" ? value : settings.replay_export_directory ?? null }); } finally { setBusy(null); } };
  return <Card className="p-6"><SectionTitle title="文件位置" description="统一管理谱面下载和回放视频导出目录。" /><div className="mt-5 space-y-4">{([ ["beatmap_download_directory", "谱面下载位置", "在线谱面默认下载到这里"], ["replay_export_directory", "回放导出位置", "生成的视频默认保存到这里"] ] as const).map(([key, title, detail]) => <div className="rounded-2xl border border-white/[0.08] bg-white/[0.035] p-4" key={key}><div className="flex items-start justify-between gap-4"><div><p className="text-base font-semibold text-white">{title}</p><p className="mt-1 text-sm text-slate-400">{detail}</p></div><Button size="sm" loading={busy === key} onClick={() => void choose(key, `选择${title}`)}><FolderOpen className="size-4" />选择</Button></div><p className="mt-3 truncate rounded-xl border border-white/[0.07] bg-black/20 px-3 py-2.5 font-mono text-sm text-slate-300">{settings[key] ?? "尚未设置"}</p></div>)}</div></Card>;
}

function TosuApiSettingsCard({ settings, onSaved }: { settings: AppSettings; onSaved: (value: AppSettings) => Promise<void> }) {
  const [value, setValue] = useState(settings.tosu_api_base_url);
  const [saving, setSaving] = useState(false);
  const save = async () => { setSaving(true); try { await onSaved({ ...settings, tosu_api_base_url: value.trim() || "http://127.0.0.1:24050" }); } finally { setSaving(false); } };
  return <Card className="p-6"><SectionTitle title="tosu API" description="配置 tosu 仪表盘与实时数据使用的 HTTP 基地址。" /><div className="mt-5 flex gap-3"><input aria-label="tosu API 地址" className="opp-input min-w-0 flex-1" onChange={(event) => setValue(event.target.value)} placeholder="http://127.0.0.1:24050" value={value} /><Button loading={saving} onClick={() => void save()} size="sm">保存地址</Button></div><p className="mt-3 text-xs text-slate-500">默认地址：http://127.0.0.1:24050。WebSocket 地址会自动派生。</p></Card>;
}

function AboutPage() { const projects = [["OPP", REPOSITORY], ["tosu", "https://github.com/tosuapp/tosu"], ["tosu-lyrics", "https://github.com/HollisMeynell/tosu-lyrics"], ["osu!", "https://github.com/ppy/osu"], ["rosu-pp", "https://github.com/MaxOhn/rosu-pp"], ["Tauri", "https://tauri.app/"]]; return <div className="space-y-5"><Card className="p-6"><p className="text-sm uppercase tracking-[0.18em] text-cyan-200">OPP Desktop</p><h2 className="mt-2 text-3xl font-semibold text-white">osu! 工具集合</h2><p className="mt-2 text-base text-slate-400">本地分析、媒体管理、回放渲染、在线数据与直播集成。</p><Button className="mt-6" onClick={() => void desktopApi.openExternal(REPOSITORY)}><ExternalLink className="size-4" />打开项目仓库</Button></Card><Card className="p-6"><SectionTitle title="感谢与关联项目" description="OPP 建立在以下开源项目、维护者和 osu! 社区用户的贡献之上。" /><div className="mt-5 grid gap-3 sm:grid-cols-2">{projects.map(([name, url]) => <button className="flex items-center justify-between rounded-xl border border-white/[0.08] bg-white/[0.025] px-4 py-3 text-left transition hover:border-cyan-300/30 hover:bg-cyan-300/[0.05]" key={name} onClick={() => void desktopApi.openExternal(url)} type="button"><span className="font-medium text-slate-100">{name}</span><ExternalLink className="size-4 text-cyan-200" /></button>)}</div><p className="mt-5 text-sm leading-6 text-slate-500">感谢所有上游维护者、贡献者以及参与测试和反馈的 osu! 社区用户。</p></Card></div>; }

export function SettingsPage() {
  const queryClient = useQueryClient(); const auth = useAuthStatus(); const settings = useSettings();
  const [tab, setTab] = useState<"general" | "about">("general"); const [disconnecting, setDisconnecting] = useState(false); const [copied, setCopied] = useState(false); const [clearing, setClearing] = useState(false);
  const updateSettings = async (value: AppSettings) => { const result = await desktopApi.updateSettings(value); queryClient.setQueryData(settingsQueryKey, result); };
  const disconnect = async () => { setDisconnecting(true); try { await desktopApi.disconnectOsu(true); queryClient.removeQueries({ queryKey: ["own-profile"] }); queryClient.removeQueries({ queryKey: ["best-scores"] }); if (auth.data) queryClient.setQueryData(authQueryKey, { ...auth.data, connected: false, user_id: null, username: null }); } finally { setDisconnecting(false); } };
  const copyCallback = async () => { if (!auth.data?.callback_url) return; await navigator.clipboard.writeText(auth.data.callback_url); setCopied(true); window.setTimeout(() => setCopied(false), 1500); };
  const clearCache = async () => { setClearing(true); try { await desktopApi.clearProfileCache(); await queryClient.invalidateQueries({ queryKey: ["own-profile"] }); await queryClient.invalidateQueries({ queryKey: ["best-scores"] }); } finally { setClearing(false); } };
  const current: AppSettings = settings.data ?? { reduce_motion: false, beatmap_download_directory: null, replay_export_directory: null, tosu_executable_path: null, tosu_api_base_url: "http://127.0.0.1:24050", launch_tosu_with_game: false, tosu_lyrics_executable_path: null, launch_tosu_lyrics_with_tosu: true };
  return <><PageHeader description="账号、目录和显示设置" eyebrow="Application" title="设置" /><div className="mb-5 flex gap-2 border-b border-white/[0.06] pb-3"><button className={`rounded-xl px-4 py-2 text-base ${tab === "general" ? "bg-cyan-300/10 text-cyan-100" : "text-slate-400"}`} onClick={() => setTab("general")} type="button">常规</button><button className={`rounded-xl px-4 py-2 text-base ${tab === "about" ? "bg-cyan-300/10 text-cyan-100" : "text-slate-400"}`} onClick={() => setTab("about")} type="button">关于</button></div>{tab === "about" ? <AboutPage /> : <div className="grid gap-5 xl:grid-cols-[1.1fr_.9fr]"><div className="space-y-5"><Card className="p-6"><div className="flex items-start justify-between"><SectionTitle title="osu! 账号" /><Badge tone={auth.data?.connected ? "success" : "warning"}>{auth.data?.connected ? "已连接" : "未连接"}</Badge></div><div className="mt-5"><DataLine label="账号" value={auth.data?.username ?? "—"} /><DataLine label="用户 ID" value={auth.data?.user_id ?? "—"} /><DataLine label="Client ID" value={auth.data?.client_id ?? "—"} /><DataLine label="回调地址" value={<button className="inline-flex items-center gap-2 font-mono text-sm text-cyan-200" onClick={copyCallback} type="button">{auth.data?.callback_url}{copied ? <Check className="size-4" /> : <Copy className="size-4" />}</button>} /></div><div className="mt-5 flex gap-3"><Button onClick={() => void desktopApi.openExternal("https://osu.ppy.sh/home/account/edit")}><ExternalLink className="size-4" />管理 OAuth</Button><Button loading={disconnecting} onClick={() => void disconnect()} variant="danger"><LogOut className="size-4" />断开账号</Button></div></Card><DirectorySettingsCard settings={current} onSaved={(value) => void updateSettings({ ...current, ...value })} /><TosuApiSettingsCard key={current.tosu_api_base_url} settings={current} onSaved={updateSettings} /></div><div className="space-y-5"><GameDirectoryCard /><Card className="p-6"><SectionTitle title="显示" /><div className="mt-5 flex items-center justify-between rounded-2xl border border-white/[0.08] bg-white/[0.035] p-4"><div className="flex items-center gap-3"><MonitorCog className="size-5 text-violet-200" /><p className="text-base font-medium text-white">减少动态效果</p></div><Switch.Root aria-label="减少动态效果" checked={current.reduce_motion} className="relative h-6 w-11 rounded-full bg-white/10 data-[state=checked]:bg-cyan-300/60" onCheckedChange={(value) => void updateSettings({ ...current, reduce_motion: value })}><Switch.Thumb className="block size-5 translate-x-0.5 rounded-full bg-white transition-transform" /></Switch.Root></div></Card><Card className="p-6"><SectionTitle title="缓存" /><Button className="mt-5" loading={clearing} onClick={() => void clearCache}><Trash2 className="size-4" />清除缓存</Button></Card></div></div>}</>;
}
