import { useState } from "react";
import * as Switch from "@radix-ui/react-switch";
import { Check, ExternalLink, FolderOpen, Trash2 } from "lucide-react";
import { useQueryClient } from "@tanstack/react-query";
import { PageHeader } from "../../shared/components/PageHeader";
import { Badge, Button, Card, DataLine, SectionTitle } from "../../shared/components/ui";
import { desktopApi } from "../../shared/lib/tauri";
import type { AppSettings, ThemeColor, ThemeMode } from "../../shared/types/osu";
import { useAuthStatus } from "../auth/api";
import { useSettings, settingsQueryKey } from "./api";

const colors: Array<[ThemeColor, string, string]> = [["cyan", "青色", "#67e8f9"], ["blue", "蓝色", "#60a5fa"], ["violet", "紫罗兰", "#a78bfa"], ["pink", "粉色", "#f472b6"], ["orange", "橙色", "#fb923c"], ["green", "绿色", "#4ade80"]];
const base: AppSettings = { reduce_motion: false, beatmap_download_directory: null, replay_export_directory: null, tosu_executable_path: null, tosu_api_base_url: "http://127.0.0.1:24050", launch_tosu_with_game: false, tosu_lyrics_executable_path: null, launch_tosu_lyrics_with_tosu: true, theme_primary: "cyan", theme_secondary: "pink", theme_mode: "dark", launch_tosu_on_game_detect: false, game_session_analysis_on_detect: true };

function Toggle({ label, description, checked, onChange }: { label: string; description: string; checked: boolean; onChange: (value: boolean) => void }) { return <div className="flex items-center justify-between gap-4 rounded-xl border border-white/[0.1] bg-white/[0.035] p-4"><div><p className="font-semibold text-slate-100">{label}</p><p className="mt-1 text-sm text-slate-300">{description}</p></div><Switch.Root checked={checked} className="relative h-6 w-11 shrink-0 rounded-full bg-slate-500 data-[state=checked]:bg-[var(--theme-primary)]" onCheckedChange={onChange}><Switch.Thumb className="block size-5 translate-x-0.5 rounded-full bg-white transition-transform data-[state=checked]:translate-x-5" /></Switch.Root></div>; }

export function SettingsPage() {
  const stored = useSettings(); const auth = useAuthStatus(); const queryClient = useQueryClient(); const [busy, setBusy] = useState(false); const settings = { ...base, ...stored.data };
  const save = async (next: AppSettings) => { setBusy(true); try { queryClient.setQueryData(settingsQueryKey, await desktopApi.updateSettings(next)); } finally { setBusy(false); } };
  const palette = (key: "theme_primary" | "theme_secondary", title: string) => <div><p className="mb-3 text-base font-bold text-slate-100">{title}</p><div className="grid grid-cols-2 gap-2 sm:grid-cols-3">{colors.map(([value, label, color]) => { const selected = settings[key] === value; return <button aria-pressed={selected} className={`flex items-center gap-2 rounded-xl border px-3 py-2.5 text-sm font-semibold transition ${selected ? "border-[var(--theme-primary)] bg-[var(--theme-primary-muted)] text-[var(--theme-primary-light)] shadow-[0_0_0_2px_var(--theme-primary-soft)]" : "border-white/10 text-slate-200 hover:bg-white/[0.06]"}`} key={value} onClick={() => void save({ ...settings, [key]: value })} type="button"><span className="size-4 rounded-full" style={{ background: color }} />{label}{selected ? <Check className="ml-auto size-4" /> : null}</button>; })}</div></div>;
  const modeButton = (mode: ThemeMode, label: string) => <button aria-pressed={settings.theme_mode === mode} className={`flex flex-1 items-center justify-center gap-2 rounded-xl border px-4 py-3 text-sm font-bold transition ${settings.theme_mode === mode ? "border-[var(--theme-primary)] bg-[var(--theme-primary)] text-slate-950 shadow-[0_0_0_3px_var(--theme-primary-soft)]" : "border-white/15 bg-white/[0.04] text-slate-200 hover:bg-white/[0.1]"}`} onClick={() => void save({ ...settings, theme_mode: mode })} type="button">{settings.theme_mode === mode ? <Check className="size-4" /> : null}{label}</button>;
  return <><PageHeader eyebrow="Application" title="设置" description="主题、游戏检测和直播自动化都在这里统一管理。" /><div className="grid gap-5 xl:grid-cols-2"><div className="space-y-5"><Card className="p-6"><div className="flex justify-between"><SectionTitle title="账户" /><Badge tone={auth.data?.connected ? "success" : "warning"}>{auth.data?.connected ? "已连接" : "未连接"}</Badge></div><div className="mt-4"><DataLine label="账户" value={auth.data?.username ?? "—"} /><DataLine label="用户 ID" value={auth.data?.user_id ?? "—"} /></div></Card><Card className="p-6"><SectionTitle title="主题" /><div className="mt-5 flex gap-2">{modeButton("dark", "深色主题")}{modeButton("light", "浅色主题")}</div><div className="mt-6 space-y-5">{palette("theme_primary", "主主题色")}{palette("theme_secondary", "副主题色")}</div></Card></div><div className="space-y-5"><Card className="p-6"><SectionTitle title="游戏检测自动化" /><div className="mt-5 space-y-3"><Toggle checked={settings.launch_tosu_on_game_detect ?? false} description="检测到 Stable 或 Lazer 运行时启动已配置的 tosu。" label="检测到游戏后启动 tosu" onChange={(value) => void save({ ...settings, launch_tosu_on_game_detect: value })} /><Toggle checked={settings.game_session_analysis_on_detect ?? true} description="检测到游戏运行时启用一场游戏的数据差异分析面板。" label="启用游戏数据差异分析" onChange={(value) => void save({ ...settings, game_session_analysis_on_detect: value })} /><Toggle checked={settings.reduce_motion} description="减少界面动画和过渡。" label="减少动态效果" onChange={(value) => void save({ ...settings, reduce_motion: value })} /></div></Card><Card className="p-6"><SectionTitle title="工具与缓存" /><div className="mt-5 flex gap-3"><Button disabled={busy} onClick={() => void desktopApi.clearProfileCache()}><Trash2 className="size-4" />清除缓存</Button><Button onClick={() => void desktopApi.openExternal("https://github.com/L1rics06/OPP")} variant="secondary"><ExternalLink className="size-4" />项目仓库</Button></div><Button className="mt-4" onClick={() => void desktopApi.chooseDirectory("选择谱面下载目录", settings.beatmap_download_directory)} variant="secondary"><FolderOpen className="size-4" />选择目录</Button></Card></div></div></>;
}
